zabbix-db-storage:
  image: busybox:latest
  volumes:
    - /var/lib/mysql

zabbix-db:
  image: monitoringartist/zabbix-db-mariadb
  volumes:
    - /backups:/backups
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - zabbix-db-storage
  environment:
    - MARIADB_USER=zabbix
    - MARIADB_PASS=my_password

zabbix-server:
  image: monitoringartist/zabbix-xxl:latest
  ports:
    - "80:80"
    - "10051:10051"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  links:
    - zabbix-db:zabbix.db
  environment:
    - ZS_DBHost=zabbix.db
    - ZS_DBUser=zabbix
    - ZS_DBPassword=my_password
